---
title: "sox2_pqs_analysis"
author: "Abigail E Hein"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pqsfinder)
library(stringi)
library(Biostrings)
library(ggplot2)
library(tidyr)
library(RColorBrewer)
```



## sox2 and shuffled sox2 datasets


```{r}
dna <- readDNAStringSet("sox2_H9_chipSeq.fa", format = "fasta")
print("No. sox2 sequences:")
length(dna)
set.seed(15)
shuffledDNA <- stri_rand_shuffle(dna)
shuffledDNA <- DNAStringSet(shuffledDNA)
print("No. shuffled sequences:")
length(shuffledDNA)
```

## predict number of G4s
  Number of random GQ's 25: 107862
  Number of predicted GQ's 25: 168681
```{r}
winners <- vector()
numWinners <- 0

for(ii in 1:length(dna)) {
  pqs <- pqsfinder(dna[[ii]], min_score = 52)
  dss <- as(pqs, "DNAStringSet")
  if (length(pqs@elementMetadata@listData[["score"]]) > 0) {
    numWinners <- numWinners +1
    winners[numWinners] <- ii
  }
}

shuffledWinners <- vector()
numShuffledWinners <- 0

for(ii in 1:length(shuffledDNA)) {
  pqs <- pqsfinder(shuffledDNA[[ii]], min_score = 52)
  dss <- as(pqs, "DNAStringSet")
  if (length(pqs@elementMetadata@listData[["score"]]) > 0) {
    numShuffledWinners <- numShuffledWinners +1
    shuffledWinners[numShuffledWinners] <- ii
  }
}
print("Number of predicted GQ sites: " )
print(numWinners)
print("Number of random GQ sites: " )
print(numShuffledWinners)
```

## Double verified GQ's


```{r}
IntersectedSitesSeq <- readDNAStringSet("Int_sox2_G4P_H9.fa", format = "fasta")

numDoubleWinners <- 0

for(ii in 1:length(IntersectedSitesSeq)) {
  Dpqs <- pqsfinder(IntersectedSitesSeq[[ii]], min_score = 52)
  #Ddss <- as(Dpqs, "DNAStringSet")
  if (length(Dpqs@elementMetadata@listData[["score"]]) > 0) {
    numDoubleWinners <-numDoubleWinners +1
  }
}

print("Number of predicted GQ's in sox2-G4 sites: " )
print(numDoubleWinners)
```


## Stats

```{r}
HitCount <- c(numWinners, numShuffledWinners)
numWinComb <- data.frame(cbind(numWinners, numShuffledWinners))
colnames(numWinComb) <- c("sox2 Sites", "shuffled Sites")
rownames(numWinComb) <- "Count"
prop.test(HitCount, rep(length(dna),2))
propsLong <-gather(numWinComb, countType, count, `sox2 Sites`:`shuffled Sites`)
```

## Venn diagram

```{r}
IntersectedSites <- toGRanges("col1-6_sorted_int_sox2-G4P_H9.bed")
NumInVivo <- length(IntersectedSites)

defNotChipSites <- length(dna)-((NumInVivo-numDoubleWinners)+numDoubleWinners+ (numWinners-numDoubleWinners))

colorPalette <- brewer.pal(3, "PuBuGn")
pie(c(NumInVivo-numDoubleWinners, numDoubleWinners, numWinners-numDoubleWinners, defNotChipSites), labels = c("In Vivo G4 Sites", "In Vivo and In Silico G4 Sites", "In Silico G4 Sites", "No G4 Sites"), border = "white", col = c('#016c59','#1c9099','#67a9cf', '#bdc9e1'))
```



## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
ggplot(propsLong, aes(y= count, x=countType, fill=countType)) + 
  geom_bar(stat = "identity", width = 0.9)+
  theme_minimal()+
  scale_fill_brewer(palette = "Reds", direction=-1)


```
